### ISSUE TITLE
Invalid token address: argument of type 'NoneType' is not iterable

### ISSUE THREAD

**Issue by sanya8923** [nessshon/token-access-control-bot#6]
Hi! It's up and running, it's fine. But when I enter the Jetton address () I get the error "Only NFT collection and Jetton master addresses are allowed:

Invalid token address:
argument of type 'NoneType' is not iterable".

I've tried to put a lot of things here, the answer is always the same
I've tried it with quotes and square brackets and quotes and square brackets and so on and so forth.

What am I missing?

**Comment by nessshon** [comment]
@sanya8923 Hi! Please write to me in telegram https://t.me/nessshon

**Comment by inozemtsev-roman** [comment]
The error appears when searching for the address of the jetton from the mainnet network.
In the .env IS_TESTNET=True needs to be changed to IS_TESTNET=False
![image](https://github.com/nessshon/token-access-control-bot/assets/24755187/9193c4d3-6185-400b-917c-8d8b0fe6bcf0)
