### ISSUE TITLE
1 wallet = 1 account

### ISSUE THREAD

**Issue by set-night** [nessshon/token-access-control-bot#7]
Eliminate the possibility of connecting 1 wallet to 2 accounts.

**Comment by nessshon** [comment]
@xelerd Hi!

Yes, that's the intended behavior. In this context, the Telegram account acts like a browser, and the wallet functions as the password and login. So if I have multiple Telegram accounts, I can identify myself with any of them, as I am the owner of the wallet. This setup allows for linking multiple accounts with the wallet.
